version: '3'
services:
  mysql_db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./dbinit/mysql-init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3307:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: converso_chat
      MYSQL_USER: user
      MYSQL_PASSWORD: test1234
      MYSQL_ROOT_PASSWORD: test1234
      SERVICE_NAME: mysql_db

  mysql_db_test:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./dbinit/mysql-test-init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/test_database:/var/lib/mysql
    ports:
      - 3308:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: converso_chat_test
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test1234
      MYSQL_ROOT_PASSWORD: test1234
      SERVICE_NAME: mysql_db_test

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src/js:/app/src/js/
    depends_on: 
      - mysql_db
      - mysql_db_test
    environment:
      - DATABASE_HOST=mysql_db
      - TEST_DATABASE_HOST=mysql_db_test

volumes:
  db_data: {}
