version: '3'
services:
  mysql_db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./dbinit/mysql-init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3307:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: converso_chat
      MYSQL_USER: user
      MYSQL_PASSWORD: wiYb&BLll3P
      MYSQL_ROOT_PASSWORD: wiYb&BLll3P
      SERVICE_TAGS: development
      SERVICE_NAME: mysql_db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src/js:/app/src/js/
    depends_on: 
      - mysql_db
    environment:
      - DATABASE_HOST=mysql_db

volumes:
  db_data: {}
